name: code-examples
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - gmt=6.5.0
  - pygmt=0.13.0
  - jupyterlab=4.2.5
  - jupyter-offlinenotebook=0.3.1
  - geopandas=1.0.1
  - folium=0.17.0
